-
  name: Deploy a docker container and configure web server # Name of Playbook
  hosts: all
  vars:
    image: nginx
    container_name: nginx
    log_driver: awslogs
    aws_region: us-east-2
    aws_log_group: ec2-nginx-cwlogs
    host_port: 80
    container_port: 80

  tasks:
  
    - name: Verify Docker is installed on target hosts
      command: docker version

    - name: Copy Web Server Static Page Template from Ansible Control Host to Target Host
      template:
        src: templates/index.html.j2
        dest: /var/index.html

    - name: Deploy a docker container and configure web server on target host
      docker_container:
        image: "{{ image }}"
        log_driver: "{{ log_driver }}"
        log_options: 
          awslogs-region: "{{ aws_region }}"
          awslogs-group: "{{ aws_log_group }}"
        name: "{{ container_name }}"
        state: started
        ports:
          - "{{host_port }}:{{ container_port}}"
        volumes:
          /var: /usr/share/nginx/html
    

          
