-
  name: Deploy a docker container and configure web server # Name of Playbook
  hosts: all # Execute this playbook in all hosts defined in inventory file
  vars: # variables
    image: nginx
    container_name: nginx
    log_driver: awslogs
    aws_region: us-east-2
    aws_log_group: ec2-nginx-cwlogs
    host_port: 80
    container_port: 80

  tasks:
  
    - name: Verify Docker is installed on target hosts  # task 1
      command: docker version

    - name: create a directory to store Web Server Static Page Templates # task 2
      file:
        name: templates
        state: directory

    - name: Copy Web Server Static Page Template from Ansible Control Host to Target Host # task 3
      template:
        src: templates/index.html.j2
        dest: ~/templates/index.html

    - name: Deploy a docker container and configure web server on target host # task 4
      docker_container:
        image: "{{ image }}"
        log_driver: "{{ log_driver }}"
        log_options: 
          awslogs-region: "{{ aws_region }}"
          awslogs-group: "{{ aws_log_group }}"
        name: "{{ container_name }}"
        state: started
        ports:
          - "{{host_port }}:{{ container_port}}"
        volumes:
        - /home/ec2-user/templates:/usr/share/nginx/html