-
  name: Deploy a docker container and configure web server # Name of Playbook
  hosts: all
  vars:
    image: nginx
    container_name: nginx

  tasks:
  
    - name: Verify Docker is installed on target hosts
      command: docker version

    - name: Deploy a docker container and configure web server on target host
      docker_container:
        image: "{{ image }}"
        name: "{{ container_name }}"
        state: started
        ports:
          - 80:80
