name: Deploy Terraform to create Infrastructure and Configure system using Ansible # The name of the workflow
on: # Specifies the trigger for this workflow
  push:
    branches:    
      - 'main'
jobs:
  check_ansible: # Name of job
    runs-on: ubuntu-latest # Configures the job to run on the latest version of an Ubuntu Linux runner. This means that the job will execute on a fresh virtual machine hosted by GitHub
    steps:
      - name: Check Ansible is installed
        run: |
          ansible --version
